apiVersion: apimanagement.gloo.solo.io/v2
kind: Portal
metadata:
  name: developer-portal
  namespace: gloo-mesh-addons
spec:
  domains:
    - developer.example.com
  portalBackendSelector:
    - selector:
        labels:
          app: gloo-mesh-portal-server
  apis:
    - routeTable:
        labels:
           portal: dev-portal
  usagePlans:
    - name: bronze
      displayName: "Bronze Plan"
      description: "A basic usage plan"
    - name: silver
      displayName: "Silver Plan"
      description: "A better usage plan"
    - name: gold
      displayName: "Gold Plan"
      description: "The best usage plan!"