apiVersion: networking.gloo.solo.io/v2
kind: RouteTable
metadata:
  name: tracks-rt
  namespace: gloo-mesh-gateways
  labels:
     portal: dev-portal
spec:
  hosts:
  - api.example.com
  virtualGateways:
  - name: istio-ingressgateway
    namespace: gloo-mesh-gateways
  portalMetadata:
    title: Catstronauts REST API
    description: REST API for Catstronauts to retrieve data for tracks, authors and modules.
  http:
  - name: tracks-api
    labels:
      security: api-key-auth
    matchers:
    - uri:
        prefix: /
    forwardTo:
      destinations:
      - ref:
          name: tracks-rest-api
          namespace: tracks
        port:
          number: 5000