apiVersion: apimanagement.gloo.solo.io/v2
kind: Portal
metadata:
  name: petstore-portal
  namespace: gloo-mesh-addons
spec:
  domains:
    - developer.example.com
  portalBackendSelector:
    - selector:
        labels:
          app: gloo-mesh-portal-server
  apis:
    - routeTable:
        labels:
           portal: demo-portal