apiVersion: security.policy.gloo.solo.io/v2
kind: ExtAuthPolicy
metadata:
  name: api-key-auth
  namespace: default
spec:
  applyToRoutes:
  - route:
      labels:
        usagePlans: dev-portal
  config:
    server:
      name: ext-auth-server
      namespace: gloo-mesh-addons
    glooAuth:
      configs:
      - apiKeyAuth:
          k8sSecretApikeyStorage:
            headersFromMetadataEntry:
              x-solo-plan: 
                name: usage-plan
            labelSelector:
              extauth: apikey