apiVersion: security.policy.gloo.solo.io/v2
kind: ExtAuthPolicy
metadata:
  name: api-key-auth
  namespace: default
spec:
  applyToRoutes:
  - route:
      labels:
        security: api-key-auth
  config:
    server:
      name: ext-auth-server
      namespace: gloo-mesh-addons
    glooAuth:
      configs:
      - apiKeyAuth:
          k8sSecretApikeyStorage:
            labelSelector:
              extauth: apikey