apiVersion: admin.gloo.solo.io/v2
kind: RateLimitServerConfig
metadata:
  name: usage-plans
  namespace: gloo-mesh-addons
spec:
  destinationServers:
  - port:
      name: grpc
    ref:
      cluster: gg-demo-single
      name: rate-limiter
      namespace: gloo-mesh-addons
  raw:
    descriptors:
    - key: usagePlan
      value: bronze
      descriptors:
      - key: userId
        rateLimit:
          requestsPerUnit: 5
          unit: MINUTE
    - key: usagePlan
      value: silver
      descriptors:
      - key: userId
        rateLimit:
          requestsPerUnit: 10
          unit: MINUTE
    - key: usagePlan
      value: gold
      descriptors:
      - key: userId
        rateLimit:
          requestsPerUnit: 50
          unit: MINUTE