apiVersion: trafficcontrol.policy.gloo.solo.io/v2
kind: RateLimitPolicy
metadata:
  name: tracks-rate-limit
  namespace: default
spec:
  applyToRoutes:
  - route:
      labels:
        route: tracks-api
  config:
    ratelimitServerConfig:
      name: usage-plans
      namespace: gloo-mesh-addons
    serverSettings:
      name: rl-server
      namespace: gloo-mesh-addons
    raw:
      rateLimits:
      - actions:  
        - requestHeaders:
            descriptorKey: usagePlan
            headerName: x-plan
        - requestHeaders:
            descriptorKey: userId
            headerName: x-user-id